/**
 * Migration manifest (M0-09) — the ordered list of migrations the runner
 * (`src/data/sqlite/migrator.ts`) applies. One entry per `drizzle-kit
 * generate` run: import its `.sql` file (inlined to a string at transform
 * time by `babel-plugin-inline-import`, see root `babel.config.js` and
 * `./sql.d.ts`) and append an entry with the next `version` number.
 *
 * `version` is this app's own sequential head, recorded verbatim into
 * `app_meta.schema_version` (05 §3.5/§10) — deliberately independent of
 * drizzle-kit's own `0000`-based file naming (drizzle-kit always starts
 * numbering at `0000`; this app's docs/tasks talk about "migration 0001"
 * meaning the first migration ever, i.e. `version: 1` here). Never reorder
 * or renumber an existing entry once it has shipped — 05 §10: "never edit
 * an applied migration".
 *
 * `sql` is one or more statements separated by drizzle-kit's own
 * `--> statement-breakpoint` marker (its convention for "run these as
 * separate statements" — needed because neither backing driver's
 * `execute()` can run more than one SQL statement per call, 05 §"P1"/08
 * §5). The runner splits on that exact marker.
 */
import migration0001Sql from './0000_app_meta_and_settings.sql';
import migration0002Sql from './0001_exercises_workouts_routines_measurements.sql';
import migration0003Sql from './0002_workout_exercises_routine_occurrence_index.sql';
import migration0004Sql from './0003_sets_routine_set_position.sql';

export interface Migration {
  /** Sequential head recorded into `app_meta.schema_version` after this migration applies. */
  version: number;
  /** The drizzle-kit-generated file this entry mirrors — for logs/errors only. */
  tag: string;
  /** Raw SQL, one or more `--> statement-breakpoint`-separated statements. */
  sql: string;
}

/**
 * Migration 0001 (M0-09 scope): `app_meta` + `settings` only, per 05 §3.5.
 *
 * Migration 0002 (M1-01 scope): the full v1 schema (05 §3.1-3.4) —
 * `exercises`, `workouts`, `workout_exercises`, `sets`, `routine_folders`,
 * `routines`, `routine_exercises`, `routine_sets`, `body_measurements`,
 * `progress_photos` — generated by drizzle-kit from `src/data/sqlite/
 * schema.ts`'s M1-01 additions. Deliberately excludes the cloud-sync
 * `[sync]` additions (`deleted_at` on exercises/routines/routine_folders,
 * `routine_folders.id` as uuid, `sync_outbox`) — those are MC-03's scope,
 * landing later; see `schema.ts`'s header comment and
 * `docs/plan/EXECUTION-LOG.md` for the full reasoning.
 *
 * Migration 0003 (M3-05 review-fix scope): adds nullable
 * `workout_exercises.routine_occurrence_index` (`schema.ts`'s own doc
 * comment on the column has the full incident writeup) — a single additive
 * `ALTER TABLE ... ADD` column, safe on existing rows (defaults `NULL`,
 * exactly "not from a routine occurrence," the correct value for every
 * `workout_exercises` row that existed before this migration).
 *
 * Migration 0004 (M3-06 review-fix scope): adds nullable
 * `sets.routine_set_position` — the identical additive pattern one level
 * down, applied to fix a real M3-06 bug (`schema.ts`'s own doc comment on
 * the column, and `domain/routine-diff.ts`'s file header, have the full
 * incident writeup: plain `sets[i] <-> routine_sets[i]` position matching
 * silently mis-correlated a matched exercise's later sets whenever
 * `WorkoutRepositoryImpl.finish()` deleted a non-trailing unchecked set and
 * renumbered the survivors). Safe on existing rows for the same reason as
 * migration 0003: `NULL` is exactly "not pinned to a routine set," the
 * correct value for every `sets` row that existed before this migration.
 */
export const MIGRATIONS: readonly Migration[] = [
  { version: 1, tag: '0000_app_meta_and_settings', sql: migration0001Sql },
  {
    version: 2,
    tag: '0001_exercises_workouts_routines_measurements',
    sql: migration0002Sql,
  },
  {
    version: 3,
    tag: '0002_workout_exercises_routine_occurrence_index',
    sql: migration0003Sql,
  },
  {
    version: 4,
    tag: '0003_sets_routine_set_position',
    sql: migration0004Sql,
  },
];
